name: Security and Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dependency-review:
    name: Dependency Review
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Dependency Review
      uses: actions/dependency-review-action@v3
      with:
        fail-on-severity: moderate

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: List packages for security audit
      run: dotnet list package --vulnerable --include-transitive
    
    - name: Run security audit
      run: dotnet list package --deprecated

  codeql-analysis:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    
    strategy:
      fail-fast: false
      matrix:
        language: [ 'csharp' ]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    # NOTE: This workflow uses advanced CodeQL configuration with custom queries.
    # If you get "CodeQL analyses from advanced configurations cannot be processed when the default setup is enabled" error:
    # 1. Go to repository Settings > Code security and analysis > Code scanning
    # 2. Disable "Default setup" for CodeQL
    # 3. This workflow provides enhanced security scanning with security-extended and security-and-quality queries
    - name: Initialize CodeQL
      uses: github/codeql-action/init@v3
      with:
        languages: ${{ matrix.language }}
        queries: security-extended,security-and-quality
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    
    - name: Build for CodeQL
      run: |
        dotnet restore
        dotnet build --configuration Release --no-restore
    
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v3